### ISSUE TITLE
Form produces server errors when adding fields

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop.org#1003]
## Steps to reproduce

1. Create a new form page
2. Add the first field to the form

## Expected behavior

Form renders with field

## Actual behavior

Internal server error in preview. If I save the draft, the error goes away.

## Notes

It looks like form functionality has continued to degrade with recent Wagtail/Django upgrades; see #925 for a similar issue from last year.

**Comment by chigby** [comment]
Error occurs in this code: https://github.com/freedomofpress/securedrop.org/blob/8a2240d9f431518d5dab64e5bcaac186e8b98875/forms/templatetags/form_tags.py#L21-L28

Which is triggered by the call to `field_extras` in the [form field template](https://github.com/freedomofpress/securedrop.org/blob/develop/forms/templates/forms/_form_field.html).  In this function, the form has not yet been saved (because a new page is being created), then the DB query in line 24 will return no records (because none have been saved yet), causing a `StopIteration` and then an uncaught `ValueError`.

The simplest way to fix this is to return `None` instead of raising an error, but I'm wondering if there's a more elegant way to add data to form fields that could be done in a way that wouldn't break the ClusterableModel-based preview feature.

**Comment by chigby** [comment]
Full traceback from my local system:

```
Traceback (most recent call last):
  File "/django/forms/templatetags/form_tags.py", line 22, in field_extras
    field_obj = filter(
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/wagtail/models/__init__.py", line 622, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/usr/local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/defaulttags.py", line 214, in render
    nodelist.append(node.render_annotated(context))
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 195, in render
    return template.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/django/forms/templatetags/form_tags.py", line 27, in field_extras
    raise ValueError('Form field {} not found in form'.format(form_field.name))
ValueError: Form field favorite_color not found in form
```

**Comment by harrislapiroff** [comment]
I'm open to whoever takes this ticket on doing some timeboxed research (say 30m) to determine if there's an easy way to access the draft form field data. If it helps, [`request.is_preview`](https://docs.wagtail.org/en/stable/topics/writing_templates.html#varying-output-between-preview-and-live) allows you to determine whether the current request is a preview. (I believe `request` should be present in `context`.)

If no approach can be identified, returning `None` or a fake object seems appropriate. We might want to add a note to the rendered page explaining that the preview output may be different from the final page.
