### ISSUE TITLE
Malicious search queries create database errors

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/securedrop.org#1004]
Saw this exception in [the logs](https://logs.freedom.press/app/discover#/doc/filebeat-*/filebeat-gke-2023.02.28?id=k9ytl4YBVUhoAbKeXV5i):

```pytb
Traceback (most recent call last):
 File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/usr/local/lib/python3.9/site-packages/wagtail/views.py", line 28, in serve
   return page.serve(request, *args, **kwargs)
 File "/usr/local/lib/python3.9/site-packages/wagtail/contrib/routable_page/models.py", line 171, in serve
   return view(request, *args, **kwargs)
 File "/usr/local/lib/python3.9/site-packages/wagtail/contrib/routable_page/models.py", line 62, in index_route
   self.get_context(request, *args, **kwargs),
 File "/django/directory/models/pages.py", line 178, in get_context
   paginator, entries = paginate(
 File "/django/common/utils.py", line 13, in paginate
   page = paginator.page(page)
 File "/usr/local/lib/python3.9/site-packages/django/core/paginator.py", line 76, in page
   number = self.validate_number(number)
 File "/usr/local/lib/python3.9/site-packages/django/core/paginator.py", line 54, in validate_number
   if number > self.num_pages:
 File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
   res = instance.__dict__[self.name] = self.func(instance)
 File "/usr/local/lib/python3.9/site-packages/django/core/paginator.py", line 103, in num_pages
   if self.count == 0 and not self.allow_empty_first_page:
 File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
   res = instance.__dict__[self.name] = self.func(instance)
 File "/usr/local/lib/python3.9/site-packages/django/core/paginator.py", line 97, in count
   return c()
 File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 412, in count
   return self.query.get_count(using=self.db)
 File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/query.py", line 528, in get_count
   number = obj.get_aggregation(using, ['__count'])['__count']
 File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/query.py", line 513, in get_aggregation
   result = compiler.execute_sql(SINGLE)
 File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
   cursor.execute(sql, params)
 File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
   return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
 File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
   return executor(sql, params, many, context)
 File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
   return self.cursor.execute(sql, params)
ValueError: A string literal cannot contain NUL (0x00) characters.
```

The query string was `search=%00igke6%22%3e%3ca%3eo5vcv&language=None&country=None&topic=None&submit.x=0&submit.y=0` which includes the  `%00` NUL character from the error.

I have some recollection of us handling this before, but I can't seem to find a ticket in any of our repos. 🤷‍♀️

**Comment by mig5** [comment]
> I have some recollection of us handling this before, but I can't seem to find a ticket in any of our repos.

Might've been https://github.com/freedomofpress/pressfreedomtracker.us/pull/1493 ?

**Comment by harrislapiroff** [comment]
Sharp eyes, @mig5! Yes, thanks. That'll be the PR to look at for reference in resolving this here. Whoever resolves this issue might also want to look proactively into other places in this project or others where we might not have this case covered.
